In [1]:
from bs4 import BeautifulSoup
import requests
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [17]:
driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
import warnings

driver = webdriver.Chrome('chromedriver.exe')

Q2 - Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time

In [18]:
url = 'https://www.bcci.tv/'
driver.get(url)

In [21]:
Int_fix = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
Int_fix

In [22]:
Int_fix.click()

In [23]:
All_Formats = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[1]')
All_Formats

In [24]:
All_Formats.click()

In [25]:
ODI = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div[3]')
ODI

In [26]:
ODI.click()

In [29]:
title = driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
len(title)

6

In [30]:
Match_title = []

for i in title:
    Match_title.append(i.text)
Match_title

['1st ODI -', '2nd ODI -', '3rd ODI -', '1st ODI -', '2nd ODI -', '3rd ODI -']

In [32]:
Place = driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')
len(Place)

6

In [33]:
Match_Place = []

for i in Place:
    Match_Place.append(i.text)
Match_Place

['1st ODI - Harare Sports Club, Harare',
 '2nd ODI - Harare Sports Club, Harare',
 '3rd ODI - Harare Sports Club, Harare',
 '1st ODI - Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 '2nd ODI - JSCA International Stadium Complex, Ranchi',
 '3rd ODI - Arun Jaitley Stadium, Delhi']

In [34]:
Series= driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
len(Series)

6

In [35]:
Series_name = []

for i in Series:
    Series_name.append(i.text)
Series_name

['INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23',
 'SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23',
 'SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23']

In [38]:
Date= driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
len(Date)

6

In [39]:
Series_Date = []

for i in Date:
    Series_Date.append(i.text)
Series_Date

['18 AUG 2022',
 '20 AUG 2022',
 '22 AUG 2022',
 '6 OCT 2022',
 '9 OCT 2022',
 '11 OCT 2022']

In [40]:
Time= driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
len(Time)

6

In [41]:
Series_Time = []

for i in Time:
    Series_Time.append(i.text)
Series_Time

['12:45 PM IST',
 '12:45 PM IST',
 '12:45 PM IST',
 '1:30 PM IST',
 '1:30 PM IST',
 '1:30 PM IST']

In [42]:
len(title),len(Place),len(Series),len(Date),len(Time)

(6, 6, 6, 6, 6)

In [45]:
India_int_fix = pd.DataFrame()
India_int_fix ['Title'] = Match_title
India_int_fix ['Place'] = Match_Place
India_int_fix ['Series'] = Series_name
India_int_fix ['Date'] = Series_Date
India_int_fix ['Time'] = Series_Time
India_int_fix

,Title,Place,Series,Date,Time
0,1st ODI -,"1st ODI - Harare Sports Club, Harare",INDIA TOUR OF ZIMBABWE ODI SERIES 2022,18 AUG 2022,12:45 PM IST
1,2nd ODI -,"2nd ODI - Harare Sports Club, Harare",INDIA TOUR OF ZIMBABWE ODI SERIES 2022,20 AUG 2022,12:45 PM IST
2,3rd ODI -,"3rd ODI - Harare Sports Club, Harare",INDIA TOUR OF ZIMBABWE ODI SERIES 2022,22 AUG 2022,12:45 PM IST
3,1st ODI -,1st ODI - Bharat Ratna Shri Atal Bihari Vajpay...,SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,6 OCT 2022,1:30 PM IST
4,2nd ODI -,"2nd ODI - JSCA International Stadium Complex, ...",SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,9 OCT 2022,1:30 PM IST
5,3rd ODI -,"3rd ODI - Arun Jaitley Stadium, Delhi",SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,11 OCT 2022,1:30 PM IST

Q 3 - Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description

In [46]:
url = 'https://www.guru99.com/'
driver.get(url)

In [47]:
Selenium = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
Selenium

In [48]:
Selenium.click()

In [49]:
Sel_Exception = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
Sel_Exception

In [50]:
Sel_Exception.click()

In [98]:
Exception_name=driver.find_elements(By.XPATH,'//table[@class="table table-striped"]//tbody//tr//td[1]')
len(Exception_name)

41

In [99]:
Name = []
for i in Exception_name[0:50]:
    Name.append(i.text)
Name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [100]:
Description=driver.find_elements(By.XPATH,'//table[@class="table table-striped"]//tbody//tr//td[2]')
len(Description)

41

In [101]:
Exp_Description = []
for i in Description[0:50]:
    Exp_Description.append(i.text)
Exp_Description

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 'Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.',
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 'It occurs when command can’t be finished when the element is invalid.',
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 'This occurs when remote WebDriver does n’t send valid commands as expected.']

In [102]:
len(Name),len(Exp_Description)

(41, 41)

In [103]:
selenium_exception = pd.DataFrame()
selenium_exception ['Exception_name'] = Name
selenium_exception ['Description'] = Exp_Description
selenium_exception

,Exception_name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

Q4 - Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)

In [147]:
driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
import warnings

driver = webdriver.Chrome('chromedriver.exe')

In [148]:
GDP = 'http://statisticstimes.com/'
driver.get(GDP)

In [149]:
Economy_button = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
Economy_button

In [150]:
Economy_button.click()

In [151]:
Economy_India = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
Economy_India

In [152]:
Economy_India.click()

In [153]:
GDP_States = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP_States

In [154]:
GDP_States.click()

In [155]:
States_name=driver.find_elements(By.XPATH,'//td[@class="name"]')
len(States_name)

68

In [167]:
States = []
for i in States_name[0:34]:
    States.append(i.text)
States

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands',
 'India']

In [168]:
States_rank=driver.find_elements(By.XPATH,'//td[@class="data1"]')
len(States_rank)

68

In [169]:
Rank = []
for i in States_rank[0:34]:
    Rank.append(i.text)
Rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '']

In [170]:
GSDP_18_19=driver.find_elements(By.XPATH,'//td[@class="data sorting_1"]')
len(GSDP_18_19)

66

In [171]:
GSDP_18_to_19 = []
for i in GSDP_18_19[0:34]:
    GSDP_18_to_19.append(i.text)
GSDP_18_to_19

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-',
 '2,332,992']

In [175]:
GSDP_19_20=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[3]')
len(GSDP_19_20)

66

In [176]:
GSDP_19_to_20 = []
for i in GSDP_19_20[0:34]:
    GSDP_19_to_20.append(i.text)
GSDP_19_to_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-',
 '-']

In [177]:
Share_18=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[5]')
len(Share_18)

66

In [178]:
Share = []
for i in Share_18[0:34]:
    Share.append(i.text)
Share

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-',
 '13.97%']

In [179]:
GDP_19=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[6]')
len(GDP_19)

66

In [180]:
GDP = []
for i in GDP_19[0:34]:
    GDP.append(i.text)
GDP

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-',
 '-']

In [182]:
len(States),len(Rank),len(GSDP_18_to_19),len(GSDP_19_to_20),len(Share),len(GDP)

(34, 34, 34, 34, 34, 34)

In [183]:
States_GDP = pd.DataFrame()
States_GDP ['States'] = States
States_GDP ['Rank'] = Rank
States_GDP['GSDP 18 to 19'] = GSDP_18_to_19
States_GDP ['GSDP 19 to 20'] = GSDP_19_to_20
States_GDP['Share'] = Share
States_GDP['GDP($ billion)'] = GDP
States_GDP

,States,Rank,GSDP 18 to 19,GSDP 19 to 20,Share,GDP($ billion)
0,Maharashtra,1,"2,632,792",-,13.94%,399.921
1,Tamil Nadu,2,"1,630,208","1,845,853",8.63%,247.629
2,Uttar Pradesh,3,"1,584,764","1,687,818",8.39%,240.726
3,Gujarat,4,"1,502,899",-,7.96%,228.290
4,Karnataka,5,"1,493,127","1,631,977",7.91%,226.806
5,West Bengal,6,"1,089,898","1,253,832",5.77%,165.556
6,Rajasthan,7,"942,586","1,020,989",4.99%,143.179
7,Andhra Pradesh,8,"862,957","972,782",4.57%,131.083
8,Telangana,9,"861,031","969,604",4.56%,130.791
9,Madhya Pradesh,10,"809,592","906,672",4.29%,122.977
10,Kerala,11,"781,653",-,4.14%,118.733
11,Delhi,12,"774,870","856,112",4.10%,117.703
12,Haryana,13,"734,163","831,610",3.89%,111.519
13,Bihar,14,"530,363","611,804",2.81%,80.562
14,Punjab,15,"526,376","574,760",2.79%,79.957
15,Odisha,16,"487,805","521,275",2.58%,74.098
16,Assam,17,"315,881",-,1.67%,47.982
17,Chhattisgarh,18,"304,063","329,180",1.61%,46.187
18,Jharkhand,19,"297,204","328,598",1.57%,45.145
19,Uttarakhand,20,"245,895",-,1.30%,37.351
20,Jammu & Kashmir,21,"155,956",-,0.83%,23.690
21,Himachal Pradesh,22,"153,845","165,472",0.81%,23.369
22,Goa,23,"73,170","80,449",0.39%,11.115
23,Tripura,24,"49,845","55,984",0.26%,7.571
24,Chandigarh,25,"42,114",-,0.22%,6.397
25,Puducherry,26,"34,433","38,253",0.18%,5.230
26,Meghalaya,27,"33,481","36,572",0.18%,5.086
27,Sikkim,28,"28,723","32,496",0.15%,4.363
28,Manipur,29,"27,870","31,790",0.15%,4.233
29,Nagaland,30,"27,283",-,0.14%,4.144
30,Arunachal Pradesh,31,"24,603",-,0.13%,3.737
31,Mizoram,32,"22,287","26,503",0.12%,3.385
32,Andaman & Nicobar Islands,33,-,-,-,-
33,India,,"2,332,992",-,13.97%,-

Q1 - Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [227]:
Wikipedia = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(github)

In [228]:
Song_Name = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[2]')
len(Song_Name)

49

In [233]:
Names = []
for i in Song_Name[0:30]:
    Names.append(i.text)
Names

['"Baby Shark Dance"[3]',
 '"Despacito"[6]',
 '"Johny Johny Yes Papa"[12]',
 '"Shape of You"[13]',
 '"See You Again"[15]',
 '"Bath Song"[20]',
 '"Phonics Song with Two Words"[21]',
 '"Uptown Funk"[22]',
 '"Learning Colors – Colorful Eggs on a Farm"[23]',
 '"Gangnam Style"[24]',
 '"Masha and the Bear – Recipe for Disaster"[29]',
 '"Wheels on the Bus"[30]',
 '"Dame Tu Cosita"[31]',
 '"Sugar"[32]',
 '"Roar"[33]',
 '"Counting Stars"[34]',
 '"Sorry"[35]',
 '"Thinking Out Loud"[36]',
 '"Axel F"[37]',
 '"Baa Baa Black Sheep"[38]',
 '"Dark Horse"[39]',
 '"Faded"[40]',
 '"Girls Like You"[41]',
 '"Let Her Go"[42]',
 '"Bailando"[43]',
 '"Lean On"[44]',
 '"Perfect"[45]',
 '"Waka Waka (This Time for Africa)"[46]',
 '"Shake It Off"[47]',
 '"Mi Gente"[48]']

In [231]:
Song_Rank = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[1]')
len(Song_Rank)

49

In [234]:
Rank = []
for i in Song_Rank[0:30]:
    Rank.append(i.text)
Rank

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '28.',
 '29.',
 '30.']

In [235]:
Artist_name = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[3]')
len(Artist_name)

49

In [242]:
Art_Name = []
for i in Artist_name[0:30]:
    Art_Name.append(i.text)
Art_Name

["Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Ed Sheeran',
 'Wiz Khalifa',
 'Cocomelon – Nursery Rhymes',
 'ChuChu TV',
 'Mark Ronson',
 'Miroshka TV',
 'Psy',
 'Get Movies',
 'Cocomelon – Nursery Rhymes',
 'El Chombo',
 'Maroon 5',
 'Katy Perry',
 'OneRepublic',
 'Justin Bieber',
 'Ed Sheeran',
 'Crazy Frog',
 'Cocomelon – Nursery Rhymes',
 'Katy Perry',
 'Alan Walker',
 'Maroon 5',
 'Passenger',
 'Enrique Iglesias',
 'Major Lazer',
 'Ed Sheeran',
 'Shakira',
 'Taylor Swift',
 'J Balvin']

In [237]:
Upload_Date = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[5]')
len(Upload_Date)

49

In [238]:
Date = []
for i in Upload_Date[0:30]:
    Date.append(i.text)
Date

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'January 30, 2017',
 'April 6, 2015',
 'May 2, 2018',
 'March 6, 2014',
 'November 19, 2014',
 'February 27, 2018',
 'July 15, 2012',
 'January 31, 2012',
 'May 24, 2018',
 'April 5, 2018',
 'January 14, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 22, 2015',
 'October 7, 2014',
 'June 16, 2009',
 'June 25, 2018',
 'February 20, 2014',
 'December 3, 2015',
 'May 31, 2018',
 'July 25, 2012',
 'April 11, 2014',
 'March 22, 2015',
 'November 9, 2017',
 'June 4, 2010',
 'August 18, 2014',
 'June 29, 2017']

In [239]:
Song_Views = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[4]')
len(Song_Views)

49

In [240]:
Views = []
for i in Song_Views[0:30]:
    Views.append(i.text)
Views

['11.09',
 '7.94',
 '6.41',
 '5.78',
 '5.59',
 '5.55',
 '4.79',
 '4.65',
 '4.60',
 '4.51',
 '4.50',
 '4.25',
 '4.01',
 '3.74',
 '3.63',
 '3.62',
 '3.57',
 '3.48',
 '3.46',
 '3.32',
 '3.32',
 '3.32',
 '3.32',
 '3.27',
 '3.25',
 '3.24',
 '3.22',
 '3.21',
 '3.19',
 '3.12']

In [245]:
most_viewed_videos = pd.DataFrame()
most_viewed_videos ['Name'] = Name
most_viewed_videos ['Rank'] = Rank
most_viewed_videos['Artist'] = Art_Name
most_viewed_videos ['Upload date'] = Date
most_viewed_videos['Views(Billions)'] = Views
most_viewed_videos

,Name,Rank,Artist,Upload date,Views(Billions)
0,Pinkfong Baby Shark - Kids' Songs & Stories,1.,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.09
1,Luis Fonsi,2.,Luis Fonsi,"January 12, 2017",7.94
2,LooLoo Kids,3.,LooLoo Kids,"October 8, 2016",6.41
3,Ed Sheeran,4.,Ed Sheeran,"January 30, 2017",5.78
4,Wiz Khalifa,5.,Wiz Khalifa,"April 6, 2015",5.59
5,Cocomelon – Nursery Rhymes,6.,Cocomelon – Nursery Rhymes,"May 2, 2018",5.55
6,ChuChu TV,7.,ChuChu TV,"March 6, 2014",4.79
7,Mark Ronson,8.,Mark Ronson,"November 19, 2014",4.65
8,Miroshka TV,9.,Miroshka TV,"February 27, 2018",4.60
9,Psy,10.,Psy,"July 15, 2012",4.51
10,Get Movies,11.,Get Movies,"January 31, 2012",4.50
11,Cocomelon – Nursery Rhymes,12.,Cocomelon – Nursery Rhymes,"May 24, 2018",4.25
12,El Chombo,13.,El Chombo,"April 5, 2018",4.01
13,Maroon 5,14.,Maroon 5,"January 14, 2015",3.74
14,Katy Perry,15.,Katy Perry,"September 5, 2013",3.63
15,OneRepublic,16.,OneRepublic,"May 31, 2013",3.62
16,Justin Bieber,17.,Justin Bieber,"October 22, 2015",3.57
17,Ed Sheeran,18.,Ed Sheeran,"October 7, 2014",3.48
18,Crazy Frog,19.,Crazy Frog,"June 16, 2009",3.46
19,Cocomelon – Nursery Rhymes,20.,Cocomelon – Nursery Rhymes,"June 25, 2018",3.32
20,Katy Perry,21.,Katy Perry,"February 20, 2014",3.32
21,Alan Walker,22.,Alan Walker,"December 3, 2015",3.32
22,Maroon 5,23.,Maroon 5,"May 31, 2018",3.32
23,Passenger,24.,Passenger,"July 25, 2012",3.27
24,Enrique Iglesias,25.,Enrique Iglesias,"April 11, 2014",3.25
25,Major Lazer,26.,Major Lazer,"March 22, 2015",3.24
26,Ed Sheeran,27.,Ed Sheeran,"November 9, 2017",3.22
27,Shakira,28.,Shakira,"June 4, 2010",3.21
28,Taylor Swift,29.,Taylor Swift,"August 18, 2014",3.19
29,J Balvin,30.,J Balvin,"June 29, 2017",3.12

I have tried to scrape the data for bill bord but i am not getting right data frame


Q6 - Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [252]:
URL = 'https:/www.billboard.com/'
driver.get(URL)

In [253]:
Chart_button = driver.find_element(By.XPATH,'/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a')
Chart_button

In [254]:
Chart_button.click()

In [257]:
Hot_100_button = driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a')
Hot_100_button

In [258]:
Hot_100_button.click()

In [ ]:
song_names=driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')

for i in song_names:

       song_name.append(i.text)

In [259]:
Song_Name=driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')
len(Song_Name)

99

In [260]:
Name = []
for i in Song_Name:
    Name.append(i.text)
Name

['About Damn Time',
 'As It Was',
 'Running Up That Hill (A Deal With God)',
 'Wait For U',
 'First Class',
 'Bad Habit',
 'Me Porto Bonito',
 'Sunroof',
 'Late Night Talking',
 'I Like You (A Happier Song)',
 'Heat Waves',
 'Cuff It',
 'The Kind Of Love We Make',
 'Wasted On You',
 'Titi Me Pregunto',
 'Stay',
 'Big Energy',
 'Alien Superstar',
 'Jimmy Cooks',
 'You Proof',
 'Church Girl',
 "I Ain't Worried",
 'Numb Little Bug',
 'She Had Me At Heads Carolina',
 "I'm That Girl",
 'Energy',
 'Glimpse Of Us',
 'Ghost',
 'Cozy',
 'Get Into It (Yuh)',
 'Moscow Mule',
 'Shivers',
 'Like I Love Country Music',
 'Vegas',
 'Cold Heart (PNAU Remix)',
 'In A Minute',
 '5 Foot 9',
 'Sticky',
 'Rock And A Hard Place',
 'Plastic Off The Sofa',
 'Fall In Love',
 "Virgo's Groove",
 'Provenza',
 'Something In The Orange',
 'Efecto',
 'Summer Renaissance',
 'Super Gremlin',
 'Last Night Lonely',
 'Never Sleep',
 'Heated',
 'Damn Strait',
 'Thique',
 'Take My Name',
 'Move',
 'Hot Shit',
 'Left And Right',
 'Son Of A Sinner',
 'Party',
 'Sleazy Flow',
 'Ojitos Lindos',
 "F.N.F. (Let's Go)",
 'Numb',
 'Pure/Honey',
 'Betty (Get Money)',
 'New Truck',
 'Despues de La Playa',
 'So Good',
 'America Has A Problem',
 'All Up In Your Mind',
 'Wishful Drinking',
 'Trouble With A Heartbreak',
 'Cooped Up',
 'Tarot',
 'Last Last',
 'Wild As Her',
 'Free Mind',
 'Unstoppable',
 'Puffin On Zootiez',
 'Truth About You',
 'Whiskey On You',
 'With A Woman You Love',
 'Victoria’s Secret',
 'Bones',
 'She Likes It',
 'At The End Of A Bar',
 'Hotel Lobby (Unc And Phew)',
 'Pick Me Up',
 'Dah Dah DahDah',
 'Thousand Miles',
 'Ghost Story',
 'Love Me More',
 'Thought You Should Know',
 '2step',
 'Massive',
 'Until I Found You',
 'Un Ratito',
 'Best Thing Since Backroads',
 'La Corriente',
 'Bzrp Music Sessions, Vol. 52']

In [264]:
Singer_Name=driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
len(Singer_Name)

99

In [265]:
Singer = []
for i in Singer_Name:
    Singer.append(i.text)
Singer

['Lizzo',
 'Harry Styles',
 'Kate Bush',
 'Future Featuring Drake & Tems',
 'Jack Harlow',
 'Steve Lacy',
 'Bad Bunny & Chencho Corleone',
 'Nicky Youre & dazy',
 'Harry Styles',
 'Post Malone Featuring Doja Cat',
 'Glass Animals',
 'Beyonce',
 'Luke Combs',
 'Morgan Wallen',
 'Bad Bunny',
 'The Kid LAROI & Justin Bieber',
 'Latto',
 'Beyonce',
 'Drake Featuring 21 Savage',
 'Morgan Wallen',
 'Beyonce',
 'OneRepublic',
 'Em Beihold',
 'Cole Swindell',
 'Beyonce',
 'Beyonce Featuring BEAM',
 'Joji',
 'Justin Bieber',
 'Beyonce',
 'Doja Cat',
 'Bad Bunny',
 'Ed Sheeran',
 'Kane Brown',
 'Doja Cat',
 'Elton John & Dua Lipa',
 'Lil Baby',
 'Tyler Hubbard',
 'Drake',
 'Bailey Zimmerman',
 'Beyonce',
 'Bailey Zimmerman',
 'Beyonce',
 'Karol G',
 'Zach Bryan',
 'Bad Bunny',
 'Beyonce',
 'Kodak Black',
 'Jon Pardi',
 'NAV, Travis Scott & Lil Baby',
 'Beyonce',
 'Scotty McCreery',
 'Beyonce',
 'Parmalee',
 'Beyonce Featuring Grace Jones & Tems',
 'Cardi B, Ye & Lil Durk',
 'Charlie Puth Featuring Jung Kook',
 'Jelly Roll',
 'Bad Bunny & Rauw Alejandro',
 'SleazyWorld Go Featuring Lil Baby',
 'Bad Bunny & Bomba Estereo',
 'Hitkidd & Glorilla',
 'Marshmello & Khalid',
 'Beyonce',
 'Yung Gravy',
 'Dylan Scott',
 'Bad Bunny',
 'Halsey',
 'Beyonce',
 'Beyonce',
 'Ingrid Andress With Sam Hunt',
 'Jason Aldean',
 'Post Malone Featuring Roddy Ricch',
 'Bad Bunny & Jhay Cortez',
 'Burna Boy',
 'Corey Kent',
 'Tems',
 'Sia',
 'Future',
 'Mitchell Tenpenny',
 'Nate Smith',
 'Justin Moore',
 'Jax',
 'Imagine Dragons',
 'Russell Dickerson & Jake Scott',
 'Chris Young With Mitchell Tenpenny',
 'Quavo & Takeoff',
 'Gabby Barrett',
 'Nardo Wick',
 'The Kid LAROI',
 'Carrie Underwood',
 'Sam Smith',
 'Morgan Wallen',
 'Ed Sheeran Featuring Lil Baby',
 'Drake',
 'Stephen Sanchez',
 'Bad Bunny',
 'Jake Owen',
 'Bad Bunny & Tony Dize',
 'Bizarrap & Quevedo']

In [336]:
Last_Week_Rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1"]')
len(Last_Week_Rank)

200

In [337]:
Last_Week = []
for i in Last_Week_Rank:
    Last_Week.append(i.text)
Last_Week

['6',
 '7',
 '1',
 '16',
 '2',
 '18',
 '3',
 '30',
 '5',
 '14',
 '4',
 '17',
 '11',
 '5',
 '8',
 '13',
 '12',
 '10',
 '7',
 '11',
 '9',
 '9',
 '10',
 '81',
 '-',
 '1',
 '17',
 '7',
 '14',
 '38',
 '16',
 '13',
 '18',
 '56',
 '13',
 '41',
 '-',
 '1',
 '15',
 '7',
 '22',
 '12',
 '-',
 '1',
 '24',
 '8',
 '19',
 '27',
 '25',
 '10',
 '-',
 '1',
 '-',
 '1',
 '21',
 '8',
 '20',
 '45',
 '-',
 '1',
 '23',
 '35',
 '26',
 '13',
 '27',
 '47',
 '30',
 '11',
 '28',
 '9',
 '29',
 '48',
 '31',
 '17',
 '48',
 '8',
 '36',
 '7',
 '33',
 '8',
 '-',
 '1',
 '37',
 '14',
 '-',
 '1',
 '34',
 '15',
 '41',
 '15',
 '44',
 '13',
 '-',
 '1',
 '39',
 '39',
 '40',
 '10',
 '-',
 '1',
 '-',
 '1',
 '32',
 '18',
 '-',
 '1',
 '46',
 '18',
 '-',
 '1',
 '45',
 '5',
 '47',
 '6',
 '56',
 '5',
 '54',
 '13',
 '53',
 '10',
 '64',
 '13',
 '66',
 '10',
 '60',
 '5',
 '-',
 '1',
 '59',
 '4',
 '67',
 '8',
 '58',
 '13',
 '62',
 '8',
 '-',
 '1',
 '-',
 '1',
 '61',
 '5',
 '63',
 '20',
 '57',
 '12',
 '73',
 '13',
 '70',
 '4',
 '75',
 '7',
 '77',
 '3',
 '74',
 '5',
 '69',
 '14',
 '82',
 '3',
 '71',
 '7',
 '90',
 '2',
 '-',
 '1',
 '80',
 '11',
 '83',
 '18',
 '86',
 '3',
 '76',
 '11',
 '-',
 '2',
 '-',
 '1',
 '50',
 '15',
 '78',
 '11',
 '84',
 '9',
 '85',
 '13',
 '68',
 '15',
 '81',
 '7',
 '88',
 '5',
 '93',
 '13',
 '72',
 '4',
 '100',
 '10',
 '98',
 '2']

In [338]:
# To find the last week rank only because above list have given last week and wks on chart list togather
L_week = [Last_Week[i] for i in range(len(Last_Week)) if i % 2 == 0]
L_week[1:99]

['1',
 '2',
 '3',
 '5',
 '4',
 '11',
 '8',
 '12',
 '7',
 '9',
 '10',
 '-',
 '17',
 '14',
 '16',
 '18',
 '13',
 '-',
 '15',
 '22',
 '-',
 '24',
 '19',
 '25',
 '-',
 '-',
 '21',
 '20',
 '-',
 '23',
 '26',
 '27',
 '30',
 '28',
 '29',
 '31',
 '48',
 '36',
 '33',
 '-',
 '37',
 '-',
 '34',
 '41',
 '44',
 '-',
 '39',
 '40',
 '-',
 '-',
 '32',
 '-',
 '46',
 '-',
 '45',
 '47',
 '56',
 '54',
 '53',
 '64',
 '66',
 '60',
 '-',
 '59',
 '67',
 '58',
 '62',
 '-',
 '-',
 '61',
 '63',
 '57',
 '73',
 '70',
 '75',
 '77',
 '74',
 '69',
 '82',
 '71',
 '90',
 '-',
 '80',
 '83',
 '86',
 '76',
 '-',
 '-',
 '50',
 '78',
 '84',
 '85',
 '68',
 '81',
 '88',
 '93',
 '72',
 '100']

In [319]:
Peak_Rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-flex-grow-1"]')
len(Peak_Rank)

200

In [335]:
Peak = []
for i in Peak_Rank:
    Peak.append(i.text)
Peak

['',
 '1',
 '',
 '1',
 '',
 '1',
 '',
 '3',
 '',
 '1',
 '',
 '1',
 '',
 '7',
 '',
 '6',
 '',
 '9',
 '',
 '4',
 '',
 '9',
 '',
 '1',
 '',
 '13',
 '',
 '13',
 '',
 '9',
 '',
 '5',
 '',
 '1',
 '',
 '3',
 '',
 '19',
 '',
 '1',
 '',
 '6',
 '',
 '22',
 '',
 '23',
 '',
 '18',
 '',
 '25',
 '',
 '26',
 '',
 '27',
 '',
 '8',
 '',
 '5',
 '',
 '30',
 '',
 '20',
 '',
 '4',
 '',
 '4',
 '',
 '26',
 '',
 '28',
 '',
 '7',
 '',
 '14',
 '',
 '38',
 '',
 '6',
 '',
 '24',
 '',
 '41',
 '',
 '35',
 '',
 '43',
 '',
 '25',
 '',
 '30',
 '',
 '34',
 '',
 '47',
 '',
 '3',
 '',
 '40',
 '',
 '50',
 '',
 '51',
 '',
 '32',
 '',
 '53',
 '',
 '22',
 '',
 '55',
 '',
 '13',
 '',
 '22',
 '',
 '56',
 '',
 '14',
 '',
 '47',
 '',
 '26',
 '',
 '62',
 '',
 '60',
 '',
 '64',
 '',
 '59',
 '',
 '66',
 '',
 '6',
 '',
 '55',
 '',
 '69',
 '',
 '70',
 '',
 '61',
 '',
 '32',
 '',
 '12',
 '',
 '18',
 '',
 '70',
 '',
 '75',
 '',
 '77',
 '',
 '74',
 '',
 '4',
 '',
 '80',
 '',
 '71',
 '',
 '82',
 '',
 '83',
 '',
 '80',
 '',
 '63',
 '',
 '86',
 '',
 '59',
 '',
 '88',
 '',
 '89',
 '',
 '15',
 '',
 '61',
 '',
 '73',
 '',
 '12',
 '',
 '48',
 '',
 '14',
 '',
 '88',
 '',
 '16',
 '',
 '72',
 '',
 '32',
 '',
 '98']

In [321]:
Weeks_on_board=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1"]')
len(Weeks_on_board)

200

In [326]:
WOB = []
for i in Weeks_on_board:
    WOB.append(i.text)
WOB

['6',
 '7',
 '1',
 '16',
 '2',
 '18',
 '3',
 '30',
 '5',
 '14',
 '4',
 '17',
 '11',
 '5',
 '8',
 '13',
 '12',
 '10',
 '7',
 '11',
 '9',
 '9',
 '10',
 '81',
 '-',
 '1',
 '17',
 '7',
 '14',
 '38',
 '16',
 '13',
 '18',
 '56',
 '13',
 '41',
 '-',
 '1',
 '15',
 '7',
 '22',
 '12',
 '-',
 '1',
 '24',
 '8',
 '19',
 '27',
 '25',
 '10',
 '-',
 '1',
 '-',
 '1',
 '21',
 '8',
 '20',
 '45',
 '-',
 '1',
 '23',
 '35',
 '26',
 '13',
 '27',
 '47',
 '30',
 '11',
 '28',
 '9',
 '29',
 '48',
 '31',
 '17',
 '48',
 '8',
 '36',
 '7',
 '33',
 '8',
 '-',
 '1',
 '37',
 '14',
 '-',
 '1',
 '34',
 '15',
 '41',
 '15',
 '44',
 '13',
 '-',
 '1',
 '39',
 '39',
 '40',
 '10',
 '-',
 '1',
 '-',
 '1',
 '32',
 '18',
 '-',
 '1',
 '46',
 '18',
 '-',
 '1',
 '45',
 '5',
 '47',
 '6',
 '56',
 '5',
 '54',
 '13',
 '53',
 '10',
 '64',
 '13',
 '66',
 '10',
 '60',
 '5',
 '-',
 '1',
 '59',
 '4',
 '67',
 '8',
 '58',
 '13',
 '62',
 '8',
 '-',
 '1',
 '-',
 '1',
 '61',
 '5',
 '63',
 '20',
 '57',
 '12',
 '73',
 '13',
 '70',
 '4',
 '75',
 '7',
 '77',
 '3',
 '74',
 '5',
 '69',
 '14',
 '82',
 '3',
 '71',
 '7',
 '90',
 '2',
 '-',
 '1',
 '80',
 '11',
 '83',
 '18',
 '86',
 '3',
 '76',
 '11',
 '-',
 '2',
 '-',
 '1',
 '50',
 '15',
 '78',
 '11',
 '84',
 '9',
 '85',
 '13',
 '68',
 '15',
 '81',
 '7',
 '88',
 '5',
 '93',
 '13',
 '72',
 '4',
 '100',
 '10',
 '98',
 '2']

In [327]:
Week_OB = [WOB[i] for i in range(len(WOB)) if i % 2 != 0]
Week_OB

['7',
 '16',
 '18',
 '30',
 '14',
 '17',
 '5',
 '13',
 '10',
 '11',
 '9',
 '81',
 '1',
 '7',
 '38',
 '13',
 '56',
 '41',
 '1',
 '7',
 '12',
 '1',
 '8',
 '27',
 '10',
 '1',
 '1',
 '8',
 '45',
 '1',
 '35',
 '13',
 '47',
 '11',
 '9',
 '48',
 '17',
 '8',
 '7',
 '8',
 '1',
 '14',
 '1',
 '15',
 '15',
 '13',
 '1',
 '39',
 '10',
 '1',
 '1',
 '18',
 '1',
 '18',
 '1',
 '5',
 '6',
 '5',
 '13',
 '10',
 '13',
 '10',
 '5',
 '1',
 '4',
 '8',
 '13',
 '8',
 '1',
 '1',
 '5',
 '20',
 '12',
 '13',
 '4',
 '7',
 '3',
 '5',
 '14',
 '3',
 '7',
 '2',
 '1',
 '11',
 '18',
 '3',
 '11',
 '2',
 '1',
 '15',
 '11',
 '9',
 '13',
 '15',
 '7',
 '5',
 '13',
 '4',
 '10',
 '2']

In [339]:
len(Name),len(Singer),len(L_week),len(Peak),len(Week_OB)

(99, 99, 100, 200, 100)

Q5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [340]:
URL = 'https://github.com/'
driver.get(URL)

In [345]:
Explore_button = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
Explore_button

In [346]:
Explore_button.click()

In [347]:
Trending_button = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
Trending_button

In [348]:
Trending_button.click()

In [349]:
Repository_title =driver.find_elements(By.XPATH,'//span[@class="text-normal"]')
len(Repository_title)

25

In [350]:
title = []
for i in Repository_title:
    title.append(i.text)
title

['pacocoursey /',
 'TheAlgorithms /',
 'InterviewReady /',
 'Alcibiades-Capital /',
 'craftzdog /',
 'hasura /',
 'eugeneyan /',
 'MatrixTM /',
 'onekey-sec /',
 'rad9800 /',
 'jwasham /',
 'toeverything /',
 'Baiyuetribe /',
 'Asabeneh /',
 'duckdb /',
 'RalfJung /',
 'datahub-project /',
 'microsoft /',
 'labmlai /',
 'iptv-org /',
 'leochen-g /',
 'openairplay /',
 'Developer-Y /',
 'withastro /',
 'gofiber /']

In [352]:
Repository_description=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
len(Repository_description)

24

In [353]:
description = []
for i in Repository_description:
    description.append(i.text)
description

['Fast, unstyled command menu React component.',
 'All Algorithms implemented in Python',
 'These are the best resources for System Design on the Internet',
 'A MEV bundle generator written in Rust',
 'My personal dotfiles',
 'Blazing fast, instant realtime GraphQL APIs on your DB with fine grained access control, also trigger webhooks on database events.',
 '📚 Papers & tech blogs by companies sharing their work on data science & machine learning in production.',
 'Best DDoS Attack Script Python3, (Cyber / DDos) Attack With 56 Methods',
 'Extract files from any kind of container formats',
 'A complete computer science study plan to become a software engineer.',
 'There can be more than Notion and Miro. Affine is a next-gen knowledge base that brings planning, sorting and creating all together. Privacy first, open-source, customizable and ready to use.',
 'Convert AI papers to GUI，Make it easy and convenient for everyone to use artificial intelligence technology。让每个人都简单方便的使用前沿人工智能技术',
 '30 Days of React challenge is a step by step guide to learn React in 30 days. It requires HTML, CSS, and JavaScript knowledge. You should be comfortable with JavaScript before you start to React. If you are not comfortable with JavaScript check out 30DaysOfJavaScript. This is a continuation of 30 Days Of JS. This challenge may take more than 100…',
 'DuckDB is an in-process SQL OLAP Database Management System',
 'A precise specification for "Rust lite / MIR plus"',
 'The Metadata Platform for the Modern Data Stack',
 'Qlib is an AI-oriented quantitative investment platform, which aims to realize the potential, empower the research, and create the value of AI technologies in quantitative investment. With Qlib, you can easily try your ideas to create better Quant investment strategies. An increasing number of SOTA Quant research works/papers are released in Qlib.',
 '🧑\u200d🏫 50! Implementations/tutorials of deep learning papers with side-by-side notes 📝; including transformers (original, xl, switch, feedback, vit, ...), optimizers (adam, adabelief, ...), gans(cyclegan, stylegan2, ...), 🎮 reinforcement learning (ppo, dqn), capsnet, distillation, ... 🧠',
 'Collection of publicly available IPTV channels from all over the world',
 '智能微秘书客户端，搭配',
 'AirPlay 2 Receiver - Python implementation',
 'List of Computer Science courses with video lectures.',
 "Build faster websites with Astro's next-gen island architecture 🏝✨",
 '⚡️ Express inspired web framework written in Go']

In [364]:
Language_used=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
len(Language_used)

20

In [365]:
Language = []
for i in Language_used:
    Language.append(i.text)
Language

['TypeScript',
 'Python',
 'Rust',
 'Lua',
 'Haskell',
 'Python',
 'Python',
 'C++',
 'TypeScript',
 'Jupyter Notebook',
 'JavaScript',
 'C++',
 'Java',
 'Python',
 'Jupyter Notebook',
 'JavaScript',
 'JavaScript',
 'Python',
 'TypeScript',
 'Go']

In [366]:
len(title),len(description),len(Language)

(25, 24, 20)

Q7 - Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/hr-recruiters-consultants
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

In [367]:
URL = 'https://www.naukri.com/hr-recruiters-consultants'
driver.get(URL)

In [374]:
Search = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
Search

In [375]:
Search.send_keys('Data science')
Search

In [376]:
Search_btn = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
Search_btn.click()

In [377]:
Recruiters_name=driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]')
len(Recruiters_name)

50

In [378]:
Name = []
for i in Recruiters_name:
    Name.append(i.text)
Name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Vaishnavi Kudalkar',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Sakshi Chhikara',
 'Ruchi Dhote',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'Avodha',
 'Priya Khare',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'Ravi Dubey']

In [379]:
Recruiters_Designation=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
len(Recruiters_Designation)

50

In [380]:
Designation = []
for i in Recruiters_Designation:
    Designation.append(i.text)
Designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Executive',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'HR Team Lead',
 'HR Manager',
 'Assistant Manager HR',
 'Senior Executive Talent Acquisition',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Company Recruitment Head',
 'Project Manager',
 'Business Development Associate',
 'Senior Manager',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'Recruitment Manager']

In [386]:
Recruiting_Company = driver.find_elements(By.XPATH,'//a[@class="ellipsis"]')
len(Recruiting_Company)

100

In [388]:
Company = []
for i in Recruiting_Company:
    Company.append(i.text)
Company[1::2]

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Codeachive learning',
 'Infinitive Software Solutions',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'SocialPrachar.com',
 'BISP Solutions',
 'BIZ INFOTECNO PRIVATE LIMITED',
 'Bristlecone India Ltd',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'Nikitha Palaparthi',
 'Independent Consultant',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'HyrEzy Talent Solutions LLP']

In [390]:
Req_Skills = driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
len(Req_Skills)

50

In [391]:
Skills = []
for i in Req_Skills:
    Skills.append(i.text)
Skills

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics, Deep Learning, statistics, Data Analytics, Data Analysis, support vector machine',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Data Science, Python, Data Analytics',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'React.js, Data Science, Java, Front End, Business Analytics, Backend, Tableau, Python, Qa Testing, Automation Testing',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Ethical Hacking, Security Operations Center, SOC, Managed Services, Data Science, Machine Learning, Artificial Intelligence, Operations Research, Education',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing',
 'Walmart Interra Skeps Expressstores indifi whitehatJr Practo Zylo Doctalk Medtrail']

In [393]:
Loc = driver.find_elements(By.XPATH,'//small[@class="ellipsis"]')
len(Loc)

48

In [394]:
Location = []
for i in Loc:
    Location.append(i.text)
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Chandigarh',
 'Pune',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Ghaziabad']

In [395]:
len(Name),len(Designation),len(Company),len(Skills),len(Location)

(50, 50, 100, 50, 48)

Q8. Scrape the details of Highest selling novels.
URL = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) PublisherNam
E) Genre

In [396]:
URL = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(URL)

In [397]:
Book_name=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[2]')
len(Book_name)

100

In [398]:
Name = []
for i in Book_name:
    Name.append(i.text)
Name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [399]:
Author_name = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[3]')
len(Author_name)

100

In [400]:
Author = []
for i in Author_name:
    Author.append(i.text)
Author

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [401]:
Volumes_sold = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[4]')
len(Volumes_sold)

100

In [402]:
sold = []
for i in Volumes_sold:
    sold.append(i.text)
sold

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [403]:
Publisher = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[5]')
len(Publisher)

100

In [405]:
Pub = []
for i in Publisher:
    Pub.append(i.text)
Pub

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [406]:
Genre = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[6]')
len(Genre)

100

In [407]:
Gen = []
for i in Genre:
    Gen.append(i.text)
Gen

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [409]:
Highest_selling_novels = pd.DataFrame()
Highest_selling_novels['Book name'] = Name
Highest_selling_novels ['Author name'] = Author
Highest_selling_novels ['Volumes sold'] = sold
Highest_selling_novels['Publisher'] = Pub
Highest_selling_novels ['Genre'] = Gen
Highest_selling_novels

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9 - Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [410]:
URL = 'https://www.imdb.com/list/ls095964455/'
driver.get(URL)

In [422]:
Name = driver.find_elements(By.XPATH,'//div[@class="lister list detail sub-list"]//h3//a')
len(Name)

100

In [423]:
Ser_Name = []
for i in Name:
    Ser_Name.append(i.text)
Ser_Name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [425]:
Span = driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
len(Span)

100

In [426]:
Span_Year = []
for i in Span:
    Span_Year.append(i.text)
Span_Year

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014–2023)',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011–2019)',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999– )',
 '(2013– )',
 '(2004–2010)',
 '(2013–2022)',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016–2022)',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019–2022)',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017–2022)',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [427]:
Genre = driver.find_elements(By.XPATH,'//span[@class="genre"]')
len(Genre)

100

In [428]:
Gen = []
for i in Genre:
    Gen.append(i.text)
Gen

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [430]:
Run_time = driver.find_elements(By.XPATH,'//span[@class="runtime"]')
len(Run_time)

100

In [431]:
Time = []
for i in Run_time:
    Time.append(i.text)
Time

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [439]:
Ratings = driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]//span[2]')
len(Ratings)

100

In [440]:
Star_Rating = []
for i in Ratings:
    Star_Rating.append(i.text)
Star_Rating

['9.2',
 '8.7',
 '8.2',
 '7.5',
 '7.6',
 '8.1',
 '6.6',
 '7.6',
 '7.6',
 '7.5',
 '8.2',
 '8.2',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.5',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.7',
 '8.7',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.5',
 '8.6',
 '8.3',
 '6.2',
 '7.4',
 '8.2',
 '7.8',
 '8.6',
 '7.9',
 '8.5',
 '9.2',
 '6.5',
 '8.1',
 '8.7',
 '8.7',
 '7.4',
 '8.4',
 '8.6',
 '7.7',
 '7.5',
 '7.7',
 '8.7',
 '6.8',
 '8.2',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.6',
 '8.3',
 '8.3',
 '7.3',
 '6.7',
 '8.4',
 '7.4',
 '8.1',
 '7.9',
 '6.8',
 '8.7',
 '8.4',
 '6.5',
 '7.9',
 '8.9',
 '7.8',
 '7.6',
 '8.9',
 '8.1',
 '8.5',
 '8.3',
 '7.2',
 '8.7',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.2',
 '8.5',
 '6.5',
 '8.1',
 '8.7',
 '9.4',
 '7.8',
 '7.4',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [451]:
Votes = driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]//span[2]')
len(Votes)

200

In [455]:
Votes_No = []
for i in Votes:
    Votes_No.append(i.text)
Votes_No[1::2]

['2,021,685',
 '1,118,344',
 '959,897',
 '286,960',
 '246,556',
 '298,646',
 '142,063',
 '300,502',
 '342,362',
 '428,410',
 '465,088',
 '792,622',
 '528,893',
 '905,896',
 '517,940',
 '165,332',
 '315,406',
 '310,614',
 '1,790,436',
 '314,585',
 '435,600',
 '524,681',
 '149,095',
 '145,508',
 '400,309',
 '222,414',
 '412,007',
 '428,216',
 '969,188',
 '671,311',
 '402,273',
 '380,006',
 '133,836',
 '123,126',
 '171,985',
 '153,164',
 '228,172',
 '489,729',
 '211,654',
 '418,848',
 '489,644',
 '62,399',
 '183,295',
 '498,526',
 '365,621',
 '75,852',
 '268,626',
 '235,805',
 '219,789',
 '215,485',
 '231,247',
 '717,623',
 '128,578',
 '332,295',
 '243,459',
 '543,895',
 '517,071',
 '454,764',
 '60,735',
 '109,811',
 '337,989',
 '73,269',
 '103,875',
 '221,894',
 '92,427',
 '91,570',
 '49,235',
 '147,213',
 '364,045',
 '302,775',
 '106,119',
 '235,252',
 '556,785',
 '103,477',
 '127,405',
 '452,547',
 '106,549',
 '227,151',
 '85,857',
 '21,760',
 '140,387',
 '153,934',
 '128,993',
 '36,571',
 '276,987',
 '119,550',
 '129,318',
 '73,217',
 '105,490',
 '193,331',
 '28,186',
 '182,406',
 '195,152',
 '721,649',
 '67,378',
 '49,269',
 '60,170',
 '193,427',
 '40,809',
 '233,425']

Q10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year

In [457]:
URL = 'https://archive.ics.uci.edu/'
driver.get(URL)

In [458]:
Dataset = driver.find_element(By.XPATH,'/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b')
Dataset.click()

In [495]:
Dataset_name = driver.find_elements(By.XPATH,'//p[@class="normal"]//b//a')
len(Dataset_name)

622

In [496]:
Name = []
for i in Dataset_name:
    Name.append(i.text)
Name

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile',
 'Badges',
 'Balance Scale',
 'Balloons',
 'Breast Cancer',
 'Breast Cancer Wisconsin (Original)',
 'Breast Cancer Wisconsin (Prognostic)',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Pittsburgh Bridges',
 'Car Evaluation',
 'Census Income',
 'Chess (King-Rook vs. King-Knight)',
 'Chess (King-Rook vs. King-Pawn)',
 'Chess (King-Rook vs. King)',
 'Chess (Domain Theories)',
 'Bach Chorales',
 'Connect-4',
 'Credit Approval',
 'Japanese Credit Screening',
 'Computer Hardware',
 'Contraceptive Method Choice',
 'Covertype',
 'Cylinder Bands',
 'Dermatology',
 'Diabetes',
 'DGP2 - The Second Data Generation Program',
 'Document Understanding',
 'EBL Domain Theories',
 'Echocardiogram',
 'Ecoli',
 'Flags',
 'Function Finding',
 'Glass Identification',
 "Haberman's Survival",
 'Hayes-Roth',
 'Heart Disease',
 'Hepatitis',
 'Horse Colic',
 'ICU',
 'Image Segmentation',
 'Internet Advertisements',
 'Ionosphere',
 'Iris',
 'ISOLET',
 'Kinship',
 'Labor Relations',
 'LED Display Domain',
 'Lenses',
 'Letter Recognition',
 'Liver Disorders',
 'Logic Theorist',
 'Lung Cancer',
 'Lymphography',
 'Mechanical Analysis',
 'Meta-data',
 'Mobile Robots',
 'Molecular Biology (Promoter Gene Sequences)',
 'Molecular Biology (Protein Secondary Structure)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "MONK's Problems",
 'Moral Reasoner',
 'Multiple Features',
 'Mushroom',
 'Musk (Version 1)',
 'Musk (Version 2)',
 'Nursery',
 'Othello Domain Theory',
 'Page Blocks Classification',
 'Optical Recognition of Handwritten Digits',
 'Pen-Based Recognition of Handwritten Digits',
 'Post-Operative Patient',
 'Primary Tumor',
 'Prodigy',
 'Qualitative Structure Activity Relationships',
 'Quadruped Mammals',
 'Servo',
 'Shuttle Landing Control',
 'Solar Flare',
 'Soybean (Large)',
 'Soybean (Small)',
 'Challenger USA Space Shuttle O-Ring',
 'Low Resolution Spectrometer',
 'Spambase',
 'SPECT Heart',
 'SPECTF Heart',
 'Sponge',
 'Statlog Project',
 'Student Loan Relational',
 'Teaching Assistant Evaluation',
 'Tic-Tac-Toe Endgame',
 'Thyroid Disease',
 'Trains',
 'University',
 'Congressional Voting Records',
 'Water Treatment Plant',
 'Waveform Database Generator (Version 1)',
 'Waveform Database Generator (Version 2)',
 'Wine',
 'Yeast',
 'Zoo',
 'Undocumented',
 'Twenty Newsgroups',
 'Australian Sign Language signs',
 'Australian Sign Language signs (High Quality)',
 'US Census Data (1990)',
 'Census-Income (KDD)',
 'Coil 1999 Competition Data',
 'Corel Image Features',
 'E. Coli Genes',
 'EEG Database',
 'El Nino',
 'Entree Chicago Recommendation Data',
 'CMU Face Images',
 'Insurance Company Benchmark (COIL 2000)',
 'Internet Usage Data',
 'IPUMS Census Database',
 'Japanese Vowels',
 'KDD Cup 1998 Data',
 'KDD Cup 1999 Data',
 'M. Tuberculosis Genes',
 'Movie',
 'MSNBC.com Anonymous Web Data',
 'NSF Research Award Abstracts 1990-2003',
 'Pioneer-1 Mobile Robot Data',
 'Pseudo Periodic Synthetic Time Series',
 'Reuters-21578 Text Categorization Collection',
 'Robot Execution Failures',
 'Synthetic Control Chart Time Series',
 'Syskill and Webert Web Page Ratings',
 'UNIX User Data',
 'Volcanoes on Venus - JARtool experiment',
 'Statlog (Australian Credit Approval)',
 'Statlog (German Credit Data)',
 'Statlog (Heart)',
 'Statlog (Landsat Satellite)',
 'Statlog (Image Segmentation)',
 'Statlog (Shuttle)',
 'Statlog (Vehicle Silhouettes)',
 'Connectionist Bench (Nettalk Corpus)',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Economic Sanctions',
 'Protein Data',
 'Cloud',
 'CalIt2 Building People Counts',
 'Dodgers Loop Sensor',
 'Poker Hand',
 'MAGIC Gamma Telescope',
 'UJI Pen Characters',
 'Mammographic Mass',
 'Forest Fires',
 'Reuters Transcribed Subset',
 'Bag of Words',
 'Concrete Compressive Strength',
 'Hill-Valley',
 'Arcene',
 'Dexter',
 'Dorothea',
 'Gisette',
 'Madelon',
 'Ozone Level Detection',
 'Abscisic Acid Signaling Network',
 'Parkinsons',
 'Character Trajectories',
 'Blood Transfusion Service Center',
 'UJI Pen Characters (Version 2)',
 'Semeion Handwritten Digit',
 'SECOM',
 'Plants',
 'Libras Movement',
 'Concrete Slump Test',
 'Communities and Crime',
 'Acute Inflammations',
 'Wine Quality',
 'URL Reputation',
 'p53 Mutants',
 'Parkinsons Telemonitoring',
 'Demospongiae',
 'Opinosis Opinion ⁄ Review',
 'Breast Tissue',
 'Cardiotocography',
 'Wall-Following Robot Navigation Data',
 'Spoken Arabic Digit',
 'Localization Data for Person Activity',
 'AutoUniv',
 'Steel Plates Faults',
 'MiniBooNE particle identification',
 'YearPredictionMSD',
 'PEMS-SF',
 'OpinRank Review Dataset',
 'Relative location of CT slices on axial axis',
 'Online Handwritten Assamese Characters Dataset',
 'PubChem Bioassay Data',
 'Record Linkage Comparison Patterns',
 'Communities and Crime Unnormalized',
 'Vertebral Column',
 'EMG Physical Action Data Set',
 'Vicon Physical Action Data Set',
 'Amazon Commerce reviews set',
 'Amazon Access Samples',
 'Reuter_50_50',
 'Farm Ads',
 'DBWorld e-mails',
 'KEGG Metabolic Relation Network (Directed)',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Bank Marketing',
 'YouTube Comedy Slam Preference Data',
 'Gas Sensor Array Drift Dataset',
 'ILPD (Indian Liver Patient Dataset)',
 'OPPORTUNITY Activity Recognition',
 'Nomao',
 'SMS Spam Collection',
 'Skin Segmentation',
 'Planning Relax',
 'PAMAP2 Physical Activity Monitoring',
 'Restaurant & consumer data',
 'CNAE-9',
 'Individual household electric power consumption',
 'seeds',
 'Northix',
 'QtyT40I10D100K',
 'Legal Case Reports',
 'Human Activity Recognition Using Smartphones',
 'One-hundred plant species leaves data set',
 'Energy efficiency',
 'Yacht Hydrodynamics',
 'Fertility',
 'Daphnet Freezing of Gait',
 '3D Road Network (North Jutland, Denmark)',
 'ISTANBUL STOCK EXCHANGE',
 'Buzz in social media',
 'First-order theorem proving',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Gas sensor arrays in open sampling settings',
 'Climate Model Simulation Crashes',
 'MicroMass',
 'QSAR biodegradation',
 'BLOGGER',
 'Daily and Sports Activities',
 'User Knowledge Modeling',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'NYSK',
 'Turkiye Student Evaluation',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'EEG Eye State',
 'Physicochemical Properties of Protein Tertiary Structure',
 'seismic-bumps',
 'banknote authentication',
 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 'YouTube Multiview Video Games Dataset',
 'Gas Sensor Array Drift Dataset at Different Concentrations',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'SkillCraft1 Master Table Dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'SML2010',
 'Bike Sharing Dataset',
 'Predict keywords activities in a online social media',
 'Thoracic Surgery Data',
 'EMG dataset in Lower Limb',
 'SUSY',
 'HIGGS',
 'Qualitative_Bankruptcy',
 'LSVT Voice Rehabilitation',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Wilt',
 'User Identification From Walking Activity',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'Leaf',
 'Dresses_Attribute_Sales',
 'Tamilnadu Electricity Board Hourly Readings',
 'Airfoil Self-Noise',
 'Wholesale customers',
 'Twitter Data set for Arabic Sentiment Analysis',
 'Combined Cycle Power Plant',
 'Urban Land Cover',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Bach Choral Harmony',
 'StoneFlakes',
 'Tennis Major Tournament Match Statistics',
 'Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 'Gesture Phase Segmentation',
 'Perfume Data',
 'BlogFeedback',
 'REALDISP Activity Recognition Dataset',
 'Newspaper and magazine images segmentation dataset',
 'AAAI 2014 Accepted Papers',
 'Gas sensor array under flow modulation',
 'Gas sensor array exposed to turbulent gas mixtures',
 'UJIIndoorLoc',
 'Sentence Classification',
 'Dow Jones Index',
 'sEMG for Basic Hand movements',
 'AAAI 2013 Accepted Papers',
 'Geographical Original of Music',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Grammatical Facial Expressions',
 'NoisyOffice',
 'MHEALTH Dataset',
 'Student Performance',
 'ElectricityLoadDiagrams20112014',
 'Gas sensor array under dynamic gas mixtures',
 'microblogPCU',
 'Firm-Teacher_Clave-Direction_Classification',
 'Dataset for Sensorless Drive Diagnosis',
 'TV News Channel Commercial Detection Dataset',
 'Phishing Websites',
 'Greenhouse Gas Observing Network',
 'Diabetic Retinopathy Debrecen Data Set',
 'HIV-1 protease cleavage',
 'Sentiment Labelled Sentences',
 'Online News Popularity',
 'Forest type mapping',
 'wiki4HE',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Chronic_Kidney_Disease',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Folio',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'Cuff-Less Blood Pressure Estimation',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Mice Protein Expression',
 'UJIIndoorLoc-Mag',
 'Heterogeneity Activity Recognition',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'HEPMASS',
 'Indoor User Movement Prediction from RSS data',
 'Open University Learning Analytics dataset',
 'default of credit card clients',
 'Mesothelioma’s disease data set',
 'Online Retail',
 'SIFT10M',
 'GPS Trajectories',
 'Detect Malacious Executable(AntiVirus)',
 'Occupancy Detection',
 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 'News Aggregator',
 'Air Quality',
 'Twin gas sensor arrays',
 'Gas sensors for home activity monitoring',
 'Facebook Comment Volume Dataset',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'Polish companies bankruptcy data',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'Dota2 Games Results',
 'Facebook metrics',
 'UbiqLog (smartphone lifelogging)',
 'NIPS Conference Papers 1987-2015',
 'HTRU2',
 'Drug consumption (quantified)',
 'Appliances energy prediction',
 'Miskolc IIS Hybrid IPS',
 'KDC-4007 dataset Collection',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'DrivFace',
 'Website Phishing',
 'YouTube Spam Collection',
 'Beijing PM2.5 Data',
 'Cargo 2000 Freight Tracking and Tracing',
 'Cervical cancer (Risk Factors)',
 'Quality Assessment of Digital Colposcopies',
 'KASANDR',
 'FMA: A Dataset For Music Analysis',
 'Air quality',
 'Epileptic Seizure Recognition',
 'Devanagari Handwritten Character Dataset',
 'Stock portfolio performance',
 'MoCap Hand Postures',
 'Early biomarkers of Parkinson�s disease based on natural connected speech',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 'PM2.5 Data of Five Chinese Cities',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Sales_Transactions_Dataset_Weekly',
 'Las Vegas Strip',
 'Eco-hotel',
 'MEU-Mobile KSD',
 'Crowdsourced Mapping',
 'gene expression cancer RNA-Seq',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'chestnut – LARVIC',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Motion Capture Hand Postures',
 'Anuran Calls (MFCCs)',
 'TTC-3600: Benchmark dataset for Turkish text categorization',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'Daily Demand Forecasting Orders',
 'Paper Reviews',
 'extention of Z-Alizadeh sani dataset',
 'Z-Alizadeh Sani',
 'Dynamic Features of VirusShare Executables',
 'IDA2016Challenge',
 'DSRC Vehicle Communications',
 'Mturk User-Perceived Clusters over Images',
 'Character Font Images',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'APS Failure at Scania Trucks',
 'Wireless Indoor Localization',
 'HCC Survival',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'University of Tehran Question Dataset 2016 (UTQD.2016)',
 'Autism Screening Adult',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'Immunotherapy Dataset',
 'Cryotherapy Dataset',
 'OCT data & Color Fundus Images of Left & Right Eyes',
 'Discrete Tone Image Dataset',
 'News Popularity in Multiple Social Media Platforms',
 'Ultrasonic flowmeter diagnostics',
 'ICMLA 2014 Accepted Papers Data Set',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'Container Crane Controller Data Set',
 'Residential Building Data Set',
 'Health News in Twitter',
 'chipseq',
 'SGEMM GPU kernel performance',
 'Repeat Consumption Matrices',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'Absenteeism at work',
 'SCADI',
 'Condition monitoring of hydraulic systems',
 'Carbon Nanotubes',
 'Optical Interconnection Network',
 'Sports articles for objectivity analysis',
 'Breast Cancer Coimbra',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 'Dishonest Internet users Dataset',
 'Victorian Era Authorship Attribution',
 'Simulated Falls and Daily Living Activities Data Set',
 'Multimodal Damage Identification for Humanitarian Computing',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Roman Urdu Data Set',
 'Avila',
 'PANDOR',
 'Drug Review Dataset (Druglib.com)',
 'Drug Review Dataset (Drugs.com)',
 'Physical Unclonable Functions',
 'Superconductivty Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Student Academics Performance',
 'Online Shoppers Purchasing Intention Dataset',
 'PMU-UD',
 "Parkinson's Disease Classification",
 'Electrical Grid Stability Simulated Data',
 'Caesarian Section Classification Dataset',
 'BAUM-1',
 'BAUM-2',
 'Audit Data',
 'BuddyMove Data Set',
 'Real estate valuation data set',
 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 'Somerville Happiness Survey',
 '2.4 GHZ Indoor Channel Measurements',
 'EMG data for gestures',
 'Parking Birmingham',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Travel Reviews',
 'Tarvel Review Ratings',
 'Rice Leaf Diseases',
 'Gas sensor array temperature modulation',
 'Facebook Live Sellers in Thailand',
 'Parkinson Dataset with replicated acoustic features',
 'Metro Interstate Traffic Volume',
 'Query Analytics Workloads Dataset',
 'Wave Energy Converters',
 'PPG-DaLiA',
 'Alcohol QCM Sensor Dataset',
 'Divorce Predictors data set',
 'Incident management process enriched event log',
 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 'MEx',
 'Beijing Multi-Site Air-Quality Data',
 'Online Retail II',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'QSAR fish toxicity',
 'QSAR aquatic toxicity',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'QSAR oral toxicity',
 'QSAR androgen receptor',
 'QSAR Bioconcentration classes dataset',
 'QSAR fish bioconcentration factor (BCF)',
 'A study of Asian Religious and Biblical Texts',
 'Real-time Election Results: Portugal 2019',
 'Bias correction of numerical prediction model temperature forecast',
 'Bar Crawl: Detecting Heavy Drinking',
 'Kitsune Network Attack Dataset',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Speaker Accent Recognition',
 'Heart failure clinical records',
 'Deepfakes: Medical Image Tamper Detection',
 'selfBACK',
 'South German Credit',
 'Exasens',
 'Swarm Behaviour',
 'Crop mapping using fused optical-radar data set',
 'BitcoinHeistRansomwareAddressDataset',
 'Facebook Large Page-Page Network',
 'Amphibians',
 'Early stage diabetes risk prediction dataset.',
 'Turkish Spam V01',
 'Stock keeping units',
 'Demand Forecasting for a store',
 'Detect Malware Types',
 'Wave Energy Converters',
 'Youtube cookery channels viewers comments in Hinglish',
 'Pedestrian in Traffic Dataset',
 'Cervical Cancer Behavior Risk',
 'Sattriya_Dance_Single_Hand_Gestures Dataset',
 'Divorce Predictors data set',
 '3W dataset',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Internet Firewall Data',
 'User Profiling and Abusive Language Detection Dataset',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Rice (Cammeo and Osmancik)',
 'Vehicle routing and scheduling problems',
 'Algerian Forest Fires Dataset',
 'Breath Metabolomics',
 'Horton General Hospital',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Gas Turbine CO and NOx Emission Data Set',
 'Activity recognition using wearable physiological measurements',
 'clickstream data for online shopping',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'Apartment for rent classified',
 ': Simulated Data set of Iraqi tourism places',
 'Nasarian CAD Dataset',
 'Monolithic Columns in Troad and Mysia Region',
 'Bar Crawl: Detecting Heavy Drinking',
 'Seoul Bike Sharing Demand',
 'Person Classification Gait Data',
 'Shill Bidding Dataset',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Bone marrow transplant: children',
 'Exasens',
 'COVID-19 Surveillance',
 'Refractive errors',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'CLINC150',
 'HCV data',
 'Taiwanese Bankruptcy Prediction',
 'South German Credit (UPDATE)',
 'IIWA14-R820-Gazebo-Dataset-10Trajectories',
 'Guitar Chords finger positions',
 'Russian Corpus of Biographical Texts',
 'Codon usage',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Myocardial infarction complications',
 'Hungarian Chickenpox Cases',
 'Simulated data for survival modelling',
 'Student Performance on an entrance examination',
 'Chemical Composition of Ceramic Samples',
 'Labeled Text Forum Threads Dataset',
 'Stock keeping units',
 'BLE RSSI dataset for Indoor localization',
 'Basketball dataset',
 'GitHub MUSAE',
 'Anticancer peptides',
 'Monolithic Columns in Troad and Mysia Region',
 'Gender by Name',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Shoulder Implant Manufacture Classification',
 'LastFM Asia Social Network',
 'Wheat kernels',
 'Productivity Prediction of Garment Employees',
 'Multi-view Brain Networks',
 'LastFM Asia Social Network',
 'Wisesight Sentiment Corpus',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Dry Bean Dataset',
 'in-vehicle coupon recommendation',
 'Gait Classification',
 'Wikipedia Math Essentials',
 'Wikipedia Math Essentials',
 'Synchronous Machine Data Set',
 'Average Localization Error (ALE) in sensor node localization process in WSNs',
 '9mers from cullpdb',
 'TamilSentiMix',
 'Accelerometer',
 'Synchronous Machine Data Set',
 'Pedal Me Bicycle Deliveries',
 'Turkish Headlines Dataset',
 'Secondary Mushroom Dataset',
 'Power consumption of Tetouan city',
 'Raisin Dataset',
 'Steel Industry Energy Consumption Dataset',
 'Gender Gap in Spanish WP',
 'Non verbal tourists data',
 'Roman Urdu Sentiment Analysis Dataset (RUSAD)',
 'TUANDROMD ( Tezpur University Android Malware Dataset)',
 'Higher Education Students Performance Evaluation Dataset',
 'Risk Factor prediction of Chronic Kidney Disease',
 'Lab Test',
 'Shoulder Implant Manufacture Classification',
 'Rocket League Skillshots Data Set',
 'Sepsis survival minimal clinical records',
 'Water Quality Prediction',
 'Traffic Flow Forecasting',
 'sentiment analysis in Saudi Arabia about distance education during Covid-19',
 'Kain Tradisional Sambas',

In [510]:
Data_type = driver.find_elements(By.XPATH,'//p[@class="normal"]//tbody//tr//td//p.normal')
len(Data_type)

0

In [486]:
Type = []
for i in Data_type:
    Type.append(i.text)
Type

['Classification (466)\nRegression (151)\nClustering (121)\nOther (56)',
 'Categorical (38)\nNumerical (422)\nMixed (55)',
 'Multivariate (480)\nUnivariate (30)\nSequential (59)\nTime-Series (126)\nText (69)\nDomain-Theory (23)\nOther (21)',
 'Life Sciences (147)\nPhysical Sciences (57)\nCS / Engineering (234)\nSocial Sciences (41)\nBusiness (45)\nGame (12)\nOther (81)',
 'Less than 10 (166)\n10 to 100 (279)\nGreater than 100 (110)',
 'Less than 100 (38)\n100 to 1000 (210)\nGreater than 1000 (339)',
 'Matrix (439)\nNon-Matrix (183)',
 'Table View  List View',
 'Abalone',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '4177 ',
 '8 ',
 '1995 ',
 'Adult',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Annealing',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '798 ',
 '38 ',
 ' ',
 'Anonymous Microsoft Web Data',
 ' ',
 'Recommender-Systems ',
 'Categorical ',
 '37711 ',
 '294 ',
 '1998 ',
 'Arrhythmia',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '452 ',
 '279 ',
 '1998 ',
 'Artificial Characters',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '6000 ',
 '7 ',
 '1992 ',
 'Audiology (Original)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 ' ',
 '1987 ',
 'Audiology (Standardized)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '69 ',
 '1992 ',
 'Auto MPG',
 'Multivariate ',
 'Regression ',
 'Categorical, Real ',
 '398 ',
 '8 ',
 '1993 ',
 'Automobile',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer, Real ',
 '205 ',
 '26 ',
 '1987 ',
 'Badges',
 'Univariate, Text ',
 'Classification ',
 ' ',
 '294 ',
 '1 ',
 '1994 ',
 'Balance Scale',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '625 ',
 '4 ',
 '1994 ',
 'Balloons',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '16 ',
 '4 ',
 ' ',
 'Breast Cancer',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '286 ',
 '9 ',
 '1988 ',
 'Breast Cancer Wisconsin (Original)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '699 ',
 '10 ',
 '1992 ',
 'Breast Cancer Wisconsin (Prognostic)',
 'Multivariate ',
 'Classification, Regression ',
 'Real ',
 '198 ',
 '34 ',
 '1995 ',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '569 ',
 '32 ',
 '1995 ',
 'Pittsburgh Bridges',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '108 ',
 '13 ',
 '1990 ',
 'Car Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '1728 ',
 '6 ',
 '1997 ',
 'Census Income',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Chess (King-Rook vs. King-Knight)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical, Integer ',
 ' ',
 '22 ',
 '1988 ',
 'Chess (King-Rook vs. King-Pawn)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '3196 ',
 '36 ',
 '1989 ',
 'Chess (King-Rook vs. King)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '28056 ',
 '6 ',
 '1994 ',
 'Chess (Domain Theories)',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Bach Chorales',
 'Univariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 '100 ',
 '6 ',
 ' ',
 'Connect-4',
 'Multivariate, Spatial ',
 'Classification ',
 'Categorical ',
 '67557 ',
 '42 ',
 '1995 ',
 'Credit Approval',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '15 ',
 ' ',
 'Japanese Credit Screening',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real, Integer ',
 '125 ',
 ' ',
 '1992 ',
 'Computer Hardware',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '209 ',
 '9 ',
 '1987 ',
 'Contraceptive Method Choice',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1473 ',
 '9 ',
 '1997 ',
 'Covertype',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '581012 ',
 '54 ',
 '1998 ',
 'Cylinder Bands',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '512 ',
 '39 ',
 '1995 ',
 'Dermatology',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '366 ',
 '33 ',
 '1998 ',
 'Diabetes',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 ' ',
 '20 ',
 ' ',
 'DGP2 - The Second Data Generation Program',
 'Data-Generator ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Document Understanding',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 'EBL Domain Theories',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Echocardiogram',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '132 ',
 '12 ',
 '1989 ',
 'Ecoli',
 'Multivariate ',
 'Classification ',
 'Real ',
 '336 ',
 '8 ',
 '1996 ',
 'Flags',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '194 ',
 '30 ',
 '1990 ',
 'Function Finding',
 ' ',
 'Function-Learning ',
 'Real ',
 '352 ',
 ' ',
 '1990 ',
 'Glass Identification',
 'Multivariate ',
 'Classification ',
 'Real ',
 '214 ',
 '10 ',
 '1987 ',
 "Haberman's Survival",
 'Multivariate ',
 'Classification ',
 'Integer ',
 '306 ',
 '3 ',
 '1999 ',
 'Hayes-Roth',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '160 ',
 '5 ',
 '1989 ',
 'Heart Disease',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '303 ',
 '75 ',
 '1988 ',
 'Hepatitis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '155 ',
 '19 ',
 '1988 ',
 'Horse Colic',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '368 ',
 '27 ',
 '1989 ',
 'ICU',
 'Multivariate, Time-Series ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Image Segmentation',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 'Internet Advertisements',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '3279 ',
 '1558 ',
 '1998 ',
 'Ionosphere',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '351 ',
 '34 ',
 '1989 ',
 'Iris',
 'Multivariate ',
 'Classification ',
 'Real ',
 '150 ',
 '4 ',
 '1988 ',
 'ISOLET',
 'Multivariate ',
 'Classification ',
 'Real ',
 '7797 ',
 '617 ',
 '1994 ',
 'Kinship',
 'Relational ',
 'Relational-Learning ',
 'Categorical ',
 '104 ',
 '12 ',
 '1990 ',
 'Labor Relations',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '57 ',
 '16 ',
 '1988 ',
 'LED Display Domain',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical ',
 ' ',
 '7 ',
 '1988 ',
 'Lenses',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '24 ',
 '4 ',
 '1990 ',
 'Letter Recognition',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '20000 ',
 '16 ',
 '1991 ',
 'Liver Disorders',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '345 ',
 '7 ',
 '1990 ',
 'Logic Theorist',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Lung Cancer',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '32 ',
 '56 ',
 '1992 ',
 'Lymphography',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '148 ',
 '18 ',
 '1988 ',
 'Mechanical Analysis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '209 ',
 '8 ',
 '1990 ',
 'Meta-data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '528 ',
 '22 ',
 '1996 ',
 'Mobile Robots',
 'Domain-Theory ',
 ' ',
 'Categorical, Integer, Real ',
 ' ',
 ' ',
 '1995 ',
 'Molecular Biology (Promoter Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '106 ',
 '58 ',
 '1990 ',
 'Molecular Biology (Protein Secondary Structure)',
 'Sequential ',
 'Classification ',
 'Categorical ',
 '128 ',
 ' ',
 ' ',
 'Molecular Biology (Splice-junction Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '3190 ',
 '61 ',
 '1992 ',
 "MONK's Problems",
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '432 ',
 '7 ',
 '1992 ',
 'Moral Reasoner',
 'Domain-Theory ',
 ' ',
 ' ',
 '202 ',
 ' ',
 '1994 ',
 'Multiple Features',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '2000 ',
 '649 ',
 ' ',
 'Mushroom',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '8124 ',
 '22 ',
 '1987 ',
 'Musk (Version 1)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '476 ',
 '168 ',
 '1994 ',
 'Musk (Version 2)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6598 ',
 '168 ',
 '1994 ',
 'Nursery',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '12960 ',
 '8 ',
 '1997 ',
 'Othello Domain Theory',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1991 ',
 'Page Blocks Classification',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '5473 ',
 '10 ',
 '1995 ',
 'Optical Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '5620 ',
 '64 ',
 '1998 ',
 'Pen-Based Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '10992 ',
 '16 ',
 '1998 ',
 'Post-Operative Patient',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '90 ',
 '8 ',
 '1993 ',
 'Primary Tumor',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '339 ',
 '17 ',
 '1988 ',
 'Prodigy',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Qualitative Structure Activity Relationships',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Quadruped Mammals',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 ' ',
 '72 ',
 '1992 ',
 'Servo',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '167 ',
 '4 ',
 '1993 ',
 'Shuttle Landing Control',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '15 ',
 '6 ',
 '1988 ',
 'Solar Flare',
 'Multivariate ',
 'Regression ',
 'Categorical ',
 '1389 ',
 '10 ',
 '1989 ',
 'Soybean (Large)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '307 ',
 '35 ',
 '1988 ',
 'Soybean (Small)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '47 ',
 '35 ',
 '1987 ',
 'Challenger USA Space Shuttle O-Ring',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '23 ',
 '4 ',
 '1993 ',
 'Low Resolution Spectrometer',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '531 ',
 '102 ',
 '1988 ',
 'Spambase',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '4601 ',
 '57 ',
 '1999 ',
 'SPECT Heart',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '267 ',
 '22 ',
 '2001 ',
 'SPECTF Heart',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '267 ',
 '44 ',
 '2001 ',
 'Sponge',
 'Multivariate ',
 'Clustering ',
 'Categorical, Integer ',
 '76 ',
 '45 ',
 ' ',
 'Statlog Project',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1992 ',
 'Student Loan Relational',
 'Domain-Theory ',
 ' ',
 ' ',
 '1000 ',
 ' ',
 '1993 ',
 'Teaching Assistant Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '151 ',
 '5 ',
 '1997 ',
 'Tic-Tac-Toe Endgame',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '958 ',
 '9 ',
 '1991 ',
 'Thyroid Disease',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real ',
 '7200 ',
 '21 ',
 '1987 ',
 'Trains',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '10 ',
 '32 ',
 '1994 ',
 'University',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '285 ',
 '17 ',
 '1988 ',
 'Congressional Voting Records',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '435 ',
 '16 ',
 '1987 ',
 'Water Treatment Plant',
 'Multivariate ',
 'Clustering ',
 'Integer, Real ',
 '527 ',
 '38 ',
 '1993 ',
 'Waveform Database Generator (Version 1)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '21 ',
 '1988 ',
 'Waveform Database Generator (Version 2)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '40 ',
 '1988 ',
 'Wine',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '178 ',
 '13 ',
 '1991 ',
 'Yeast',
 'Multivariate ',
 'Classification ',
 'Real ',
 '1484 ',
 '8 ',
 '1996 ',
 'Zoo',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '101 ',
 '17 ',
 '1990 ',
 'Undocumented',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Twenty Newsgroups',
 'Text ',
 ' ',
 ' ',
 '20000 ',
 ' ',
 '1999 ',
 'Australian Sign Language signs',
 'Multivariate, Time-Series ',
 'Classification ',
 'Categorical, Real ',
 '6650 ',
 '15 ',
 '1999 ',
 'Australian Sign Language signs (High Quality)',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '2565 ',
 '22 ',
 '2002 ',
 'US Census Data (1990)',
 'Multivariate ',
 'Clustering ',
 'Categorical ',
 '2458285 ',
 '68 ',
 ' ',
 'Census-Income (KDD)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '299285 ',
 '40 ',
 '2000 ',
 'Coil 1999 Competition Data',
 'Multivariate ',
 ' ',
 'Categorical, Real ',
 '340 ',
 '17 ',
 '1999 ',
 'Corel Image Features',
 'Multivariate ',
 ' ',
 'Real ',
 '68040 ',
 '89 ',
 '1999 ',
 'E. Coli Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'EEG Database',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer, Real ',
 '122 ',
 '4 ',
 '1999 ',
 'El Nino',
 'Spatio-temporal ',
 ' ',
 'Integer, Real ',
 '178080 ',
 '12 ',
 '1999 ',
 'Entree Chicago Recommendation Data',
 'Transactional, Sequential ',
 'Recommender-Systems ',
 'Categorical ',
 '50672 ',
 ' ',
 '2000 ',
 'CMU Face Images',
 'Image ',
 'Classification ',
 'Integer ',
 '640 ',
 ' ',
 '1999 ',
 'Insurance Company Benchmark (COIL 2000)',
 'Multivariate ',
 'Regression, Description ',
 'Categorical, Integer ',
 '9000 ',
 '86 ',
 '2000 ',
 'Internet Usage Data',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '10104 ',
 '72 ',
 '1999 ',
 'IPUMS Census Database',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '256932 ',
 '61 ',
 '1999 ',
 'Japanese Vowels',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '640 ',
 '12 ',
 ' ',
 'KDD Cup 1998 Data',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '191779 ',
 '481 ',
 '1998 ',
 'KDD Cup 1999 Data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '4000000 ',
 '42 ',
 '1999 ',
 'M. Tuberculosis Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'Movie',
 'Multivariate, Relational ',
 ' ',
 ' ',
 '10000 ',
 ' ',
 '1999 ',
 'MSNBC.com Anonymous Web Data',
 'Sequential ',
 ' ',
 'Categorical ',
 '989818 ',
 ' ',
 ' ',
 'NSF Research Award Abstracts 1990-2003',
 'Text ',
 ' ',
 ' ',
 '129000 ',
 ' ',
 '2003 ',
 'Pioneer-1 Mobile Robot Data',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Real ',
 ' ',
 ' ',
 '1999 ',
 'Pseudo Periodic Synthetic Time Series',
 'Univariate, Time-Series ',
 ' ',
 ' ',
 '100000 ',
 ' ',
 '1999 ',
 'Reuters-21578 Text Categorization Collection',
 'Text ',
 'Classification ',
 'Categorical ',
 '21578 ',
 '5 ',
 '1997 ',
 'Robot Execution Failures',
 'Multivariate, Time-Series ',
 'Classification ',
 'Integer ',
 '463 ',
 '90 ',
 '1999 ',
 'Synthetic Control Chart Time Series',
 'Time-Series ',
 'Classification, Clustering ',
 'Real ',
 '600 ',
 ' ',
 '1999 ',
 'Syskill and Webert Web Page Ratings',
 'Multivariate, Text ',
 'Classification ',
 'Categorical ',
 '332 ',
 '5 ',
 '1998 ',
 'UNIX User Data',
 'Text, Sequential ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Volcanoes on Venus - JARtool experiment',
 'Image ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Statlog (Australian Credit Approval)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '14 ',
 ' ',
 'Statlog (German Credit Data)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1000 ',
 ...]